name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Linter checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        name: Dependencies installing
      - run: npm run lint
        name: Linters checking

      - if: failure()
        run: |
           echo "Lint checking is failed."
           exit 1

  test:
    name: Test checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
        name: Dependencies installing
      - run: npm run test
        name: Test checking

      - if: failure()
        run: |
          echo "Test checking is failed."
          exit 1